// Generated by build-sta.cjs. Release: 0.2.2
const VERSION="0.2.2";
const ASSETS={
  "./icon192.png": "b6ce43a9695728bc4d83fa3a5d731ad016200043f0fcab6328433256a5bb5390",
  "./icon512.png": "1a5a5dc1c57076e852d8b6fef8320784e9f8cba7e7739a841a9518ed4d4163a4",
  "./index.html": "7b82db641ac9579c7d607c688596d542264e8f151434cdddd17311a9ade6e0fc",
  "./language-guide.png": "a5070fddf3102d64954129141e551fa53031e105e9f3e239919ca656be4a2e5c",
  "./manifest.json": "c7d56c843282e1a5b26f3d6bc4c3f854363f2ba768115c45cff074f4f291714e",
  "./phrases.js": "7ff48dcea02932c908e51a55b66582beca188615639dc37dffb1a75279cc8592",
  "./pwa-update.js": "a982317516c8244798c3f030a2da6c40b3ddece5be3f3957b833481e8bb94447",
  "./route-map.png": "87d3cebd189abf7d2de8808233774f8003bb56f40cb6b930ebc6d51010d6847f"
};
// Each release has its own cache; failed downloads never remove a working release.
const CACHE_NAME = 'sta-' + VERSION + '-' + ASSETS['./index.html'].slice(0,12);
const assetURLs = new Map(Object.entries(ASSETS).map(([file,hash])=>[new URL(file,self.registration.scope).href,hash]));
self.addEventListener('install',event=>{
  event.waitUntil((async()=>{
    const responses=[];
    // Stage and verify every byte before writing the new cache.
    for(const [url,hash] of assetURLs){
      const response=await fetch(new Request(url,{cache:'no-store'}));
      if(!response.ok || response.redirected) throw new Error('Asset download failed');
      const digest=await crypto.subtle.digest('SHA-256',await response.clone().arrayBuffer());
      const actual=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');
      if(actual!==hash) throw new Error('Incomplete or mixed release');
      responses.push([url,response]);
    }
    const cache=await caches.open(CACHE_NAME);
    for(const [url,response] of responses) await cache.put(url,response);
    // No automatic skipWaiting: the update button performs the switch.
  })());
});
self.addEventListener('activate',event=>{
  // Retain previous caches as a fallback; never delete unrelated apps' caches.
  event.waitUntil(self.clients.claim());
});
self.addEventListener('message',event=>{
  if(event.data?.type==='ACTIVATE') event.waitUntil(self.skipWaiting());
});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url);
  const home=new URL('./',self.registration.scope);
  const index=new URL('./index.html',home);
  let key=url.href;
  if(event.request.mode==='navigate' && (url.pathname===home.pathname || url.pathname===index.pathname) && url.origin===home.origin)key=index.href;
  if(!assetURLs.has(key))return;
  event.respondWith((async()=>{
    const cache=await caches.open(CACHE_NAME);
    const response=await cache.match(key);
    return response || new Response('STAの保存データがありません。オンラインで更新してください。',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});
  })());
});
